"""CSV export with spreadsheet formula-injection sanitization and a
compact PDF dataset report built with fpdf2."""

import csv
import io
from collections.abc import Iterator

import sqlalchemy as sa
from sqlalchemy import Engine

from app.models.dataset import Dataset, DatasetVersion
from app.models.workspace import Report
from app.services.datasets import tables

CSV_CHUNK = 5000
FORMULA_PREFIXES = ("=", "+", "-", "@")


def _safe_cell(v) -> str:
    s = "" if v is None else (v.isoformat() if hasattr(v, "isoformat") else str(v))
    if s.startswith(FORMULA_PREFIXES):
        return "'" + s
    return s


def export_csv(engine: Engine, version: DatasetVersion, max_rows: int = 100_000) -> Iterator[str]:
    """Stream the version's physical table as sanitized CSV chunks."""
    table = tables.reflect_table(engine, version.table_name)
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow([c.name for c in table.c])
    yield buf.getvalue()

    with engine.connect() as conn:
        result = conn.execution_options(stream_results=True).execute(
            sa.select(table).limit(max_rows)
        )
        while chunk := result.fetchmany(CSV_CHUNK):
            buf = io.StringIO()
            writer = csv.writer(buf)
            for row in chunk:
                writer.writerow([_safe_cell(v) for v in row])
            yield buf.getvalue()


def _txt(s: str) -> str:
    """Built-in helvetica is latin-1 only — transliterate Unicode."""
    s = str(s).replace("—", "-").replace("•", "-").replace("·", "-").replace("σ", "sigma")
    return s.encode("latin-1", errors="replace").decode("latin-1")


def build_pdf_report(
    engine: Engine,
    *,
    dataset: Dataset,
    version: DatasetVersion,
    kpis: list,
    insights: list,
    generated_by: str,
) -> bytes:
    """One-page-summary style PDF: header, meta, KPIs, insights, top columns."""
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("helvetica", "B", 18)
    pdf.cell(0, 10, _txt(f"Data Report: {dataset.name}"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(90)
    pdf.cell(0, 6, _txt(f"Generated by {generated_by}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(
        0, 6,
        _txt(f"Source: {dataset.original_filename} | {dataset.row_count:,} rows | "
             f"{dataset.column_count} columns | quality {dataset.quality_score or 0:.0f}/100"),
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.ln(4)

    pdf.set_text_color(0)
    pdf.set_font("helvetica", "B", 13)
    pdf.cell(0, 8, "Column profile", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 8)
    cols = sorted(version.columns, key=lambda c: c.ordinal)[:14]
    pdf.set_fill_color(240, 240, 240)
    widths = [50, 25, 30, 30, 30]
    for w, h in zip(widths, ["Column", "Type", "Nulls", "Distinct", "Mean"]):
        pdf.cell(w, 6, h, border=1, fill=True)
    pdf.ln()
    for c in cols:
        row = [
            c.normalized_name[:28],
            c.inferred_type,
            f"{c.null_count:,}",
            f"{c.distinct_count:,}",
            f"{c.mean:,.1f}" if c.mean is not None else "-",
        ]
        for w, cell in zip(widths, row):
            pdf.cell(w, 6, _txt(cell), border=1)
        pdf.ln()
    pdf.ln(4)

    if kpis:
        pdf.set_font("helvetica", "B", 13)
        pdf.cell(0, 8, "KPIs", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 10)
        for k in kpis:
            pdf.cell(0, 6, _txt(f"- {k}"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    if insights:
        pdf.set_font("helvetica", "B", 13)
        pdf.cell(0, 8, "Insights", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 10)
        for ins in insights[:10]:
            pdf.multi_cell(
                pdf.epw, 5,
                _txt(f"[{ins.severity.value.upper()}] {ins.title}: {ins.body}"),
            )

    return bytes(pdf.output())
